config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:new, :create, :index, :show]
  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User",
                       foreign_key: "user_id"
  has_and_belongs_to_many :attendees, class_name: "User", 
                                      association_foreign_key: "user_id",
                                      join_table: "attended_events_attendees"
  scope :past, -> {where("date < ?", DateTime.now)}
  scope :upcoming, -> {where("date > ?", DateTime.now)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_and_belongs_to_many :attended_events, class_name: "Event",
                                      association_foreign_key: "event_id",
                                      join_table: "attended_events_attendees"
  
  def upcoming_events
    self.events.where("date > ?", DateTime.now)
  end
  
  def previous_events
    self.events.where("date < ?", DateTime.now)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      flash.notice = "Event '#{@event.name}' created!"
      redirect_to event_path(@event)
    else
      flash.notice = "Event '#{@event.name}' creation failed."
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find(params[:user][:id])
    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "User Not Found"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.notice = "User '#{@user.name}' created!"
      redirect_to user_path(@user)
    else
      flash.notice = "User '#{@user.name}' creation failed."
      render :new
    end
  end

  def show 
    @user = User.find(params[:id])
    
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<% if current_user%>
  <%= link_to "New Event", new_event_path%>
<% end%>

<h3>Upcoming Events</h3>
  
  <% @events.upcoming.each do |event| %>
    <h4><%= event.name %></h4>
    <%= event.description%><br>
    <%= event.date%>
    <br><br>
  <% end %>
  


<h3>Past Events</h3>
  
  <% @events.past.each do |event| %>
    <h4><%= event.name %></h4>
    <%= event.description%><br>
    <%= event.date%>
    <br><br>
  <% end %>
  

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= form_with model: @event do |f|%>
  <%= f.label :name, "Name:"%>
  <%= f.text_field :name%>
  <br>
  <%= f.label :description, "Event Description:"%>
  <%= f.text_field :description%>
  <br>
  <%= f.date_select :date %>
  <br>
  <%= f.submit "Create"%>
<% end %>

app/views/events/show.html.erb
<h1><%=@event.name%></h1>
<br>
<h3><%=@event.description%></h3>
<br>
<p>Attendees:</p>
<% @event.attendees.each do |attendee|%>
  <%= attendee.name%>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <% if current_user%>
      Logged in as <%= current_user.name%><br>
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Log In", login_path %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= form_with model: @user do |f|%>
  <%= f.label :name, "Name:"%>
  <%= f.text_field :name%>
  <%= f.submit "Create"%>
<% end %>

app/views/users/show.html.erb
<h1>Profile for <%=@user.name%></h1>
<br>
<h3><%=@user.name%>'s events:</h3>
<h4>Upcoming Events</h4>
  <ul>
  <% @user.upcoming_events.each do |event| %>
    <li><%= event.name %></li>
  <% end %>
  </ul>
<h4>Previous Events</h4>
  <ul>
  <% @user.previous_events.each do |event| %>
    <li><%= event.name %></li>
  <% end %>
  </ul>